'use strict';

// ============================================================
// WORD LISTS
// 45 topics × 40 words each. Words are uppercase, no spaces/hyphens.
// Shorter words work for Easy; all words work for Hard.
// ============================================================
const WORD_LISTS = {

  boy: {
    'Dinosaurs': [
      'TREX','RAPTOR','FOSSIL','CLAW','SCALES','STOMP','ROAR','BONES',
      'SPIKE','HORN','ARMOR','NEST','EGGS','FANG','TAIL','HERD','PREY',
      'DINO','TEETH','JUNGLE','SWAMP','HUNT','SWIFT','BEAST','CRATER',
      'STEGO','TRICERATOPS','BRONTOSAURUS','VELOCIRAPTOR','ANKYLOSAUR',
      'PTERODACTYL','SPINOSAURUS','DIPLODOCUS','IGUANODON','ALLOSAURUS',
      'HERBIVORE','CARNIVORE','PREDATOR','EXTINCT','JURASSIC'
    ],
    'Space': [
      'ROCKET','PLANET','GALAXY','METEOR','NEBULA','SATURN','COMET',
      'ORBIT','STAR','MOON','MARS','PROBE','LAUNCH','SUIT','GRAVITY',
      'ASTEROID','OXYGEN','MODULE','CAPSULE','THRUST','CRATER','SOLAR',
      'LUNAR','COSMOS','SHUTTLE','TELESCOPE','ASTRONAUT','SPACEWALK',
      'BLACKHOLE','SUPERNOVA','WORMHOLE','UNIVERSE','INFRARED','SATELLITE',
      'REENTRY','LIFTOFF','LAUNCHPAD','DOCKING','MISSION','VACUUM'
    ],
    'Sports': [
      'FOOTBALL','BASEBALL','SOCCER','HOCKEY','TENNIS','SWIMMING',
      'TROPHY','ATHLETE','CHAMPION','VICTORY','REFEREE','PENALTY',
      'TACKLE','SPRINT','SCORE','TEAM','COACH','GOAL','MEDAL','REBOUND',
      'PITCHER','GOALIE','ASSIST','SERVE','VOLLEY','DRIBBLE','OFFENSE',
      'DEFENSE','STADIUM','TIMEOUT','OVERTIME','PLAYOFFS','TOURNAMENT',
      'TRAINING','ENDZONE','FASTBALL','SLAP SHOT','FREESTYLE','RELAY','VAULT'
    ],
    'Superheroes': [
      'HERO','VILLAIN','CAPE','MASK','SHIELD','LASER','POWER','STRENGTH',
      'FLIGHT','DEFEND','RESCUE','SIDEKICK','GADGET','ARMOR','JUSTICE',
      'LEAP','PUNCH','KICK','SWIFT','FORCE','STEALTH','THUNDER','BLAZE',
      'COSMIC','INVINCIBLE','AVENGER','MUTANT','TELEPATHY','KRYPTONITE',
      'RADIOACTIVE','SERUM','LABORATORY','TRANSFORM','DIMENSION','PORTAL',
      'NEMESIS','CIVILIAN','HIDEOUT','UTILITY','HEADQUARTERS'
    ],
    'Vehicles': [
      'RACECAR','MONSTER','DRAGSTER','FORMULA','ENGINE','TURBO','WHEELS',
      'DRIVER','NITRO','SPEEDWAY','THROTTLE','CHASSIS','PISTON','BURNOUT',
      'GEARBOX','TRUCK','MUSCLE','RALLY','DRIFT','CLUTCH','BRAKE','FUEL',
      'BOOST','TORQUE','EXHAUST','SUPERCAR','TRANSMISSION','HORSEPOWER',
      'SUSPENSION','AERODYNAMIC','TRACTION','AXLE','CRANKSHAFT','CARBURETOR',
      'OVERDRIVE','MANIFOLD','INTERCOOLER','DIFFERENTIAL','DRIVESHAFT','INTAKE'
    ],
    'Pirates': [
      'TREASURE','CAPTAIN','SWORD','CANNON','ANCHOR','PLANK','SKULL',
      'GALLEON','COMPASS','DOUBLOON','PARROT','BUCCANEER','CUTLASS',
      'SCALLYWAG','BOOTY','JOLLY','COAST','ISLAND','BURIED','CREW',
      'MAST','FLAG','COVE','LOOT','ROGER','BRIGANTINE','MAINSAIL',
      'RIGGING','BROADSIDE','QUARTERMASTER','NAVIGATOR','FREEBOOTER',
      'PLUNDER','CORSAIR','SWASHBUCKLE','MAROON','PORTHOLE','STARBOARD',
      'LANDLUBBER','AHOY'
    ],
    'Robots': [
      'ANDROID','CIRCUIT','LASER','SENSOR','MOTOR','BATTERY','PROGRAM',
      'DIGITAL','METAL','CYBORG','VOLTAGE','ANTENNA','TITANIUM','SCANNER',
      'SYSTEM','GEAR','BOLT','STEEL','WIRE','SERVO','POWER','LOGIC',
      'BINARY','CHIP','REACTOR','PROCESSOR','HYDRAULIC','PNEUMATIC',
      'ALGORITHM','INTERFACE','DATABANK','MAINFRAME','ACTUATOR','ENCODER',
      'FEEDBACK','CONTROLLER','PROTOTYPE','AUTONOMOUS','FIRMWARE','RECHARGE'
    ],
    'Gaming': [
      'PLAYER','QUEST','LEVEL','DUNGEON','SWORD','SHIELD','ARMOR',
      'POTION','CASTLE','WIZARD','GOBLIN','RESPAWN','CONSOLE','JOYSTICK',
      'MISSION','AVATAR','VICTORY','DRAGON','HEALTH','MAGIC','BOSS',
      'SPAWN','LOOT','SCORE','CHEAT','MULTIPLAYER','ACHIEVEMENT','SPEEDRUN',
      'INVENTORY','CHECKPOINT','LEADERBOARD','CONTROLLER','SANDBOX',
      'STRATEGY','POWERUP','CRAFTING','RESOURCE','UPGRADE','DIFFICULTY','HIGHSCORE'
    ],
    'Wild Animals': [
      'LION','TIGER','ELEPHANT','GORILLA','CHEETAH','RHINO','HIPPO',
      'CROCODILE','PANTHER','LEOPARD','JAGUAR','PYTHON','COBRA','VULTURE',
      'BUFFALO','HYENA','BABOON','WARTHOG','MONGOOSE','MAMBA','GIRAFFE',
      'ZEBRA','LYNX','PUMA','WOLF','WOLVERINE','WILDEBEEST','BUSHBUCK',
      'MANDRILL','CARACAL','SERVAL','AARDVARK','PANGOLIN','OKAPI',
      'SPRINGBOK','IMPALA','HORNBILL','MEERKAT','DINGO','TAPIR'
    ],
    'Ninjas': [
      'NINJA','SAMURAI','KATANA','SHURIKEN','SENSEI','DOJO','STEALTH',
      'SHADOW','WARRIOR','DRAGON','BLADE','SCROLL','HONOR','COMBAT',
      'STRIKE','SWIFT','SILENT','DISGUISE','JUMP','KICK','THROW','HIDE',
      'SNEAK','DODGE','FLIP','NUNCHAKU','THROWING STAR','MEDITATION',
      'BUSHIDO','SHINOBI','KUNOICHI','EXPLOSIVE','GRAPPLE','INFILTRATE',
      'VANISH','DEFLECT','PARRY','COUNTERATTACK','AMBUSH','FORMATION'
    ],
    'Sharks': [
      'SHARK','HAMMERHEAD','MAKO','WHALE','DOLPHIN','OCTOPUS','LOBSTER',
      'CORAL','JELLYFISH','STARFISH','SEAWEED','TSUNAMI','SUBMARINE',
      'MANATEE','NARWHAL','BARRACUDA','TUNA','CRAB','REEF','ORCA',
      'SQUID','CURRENT','ANEMONE','SWORDFISH','ANCHOR','LEMON SHARK',
      'BULL SHARK','TIGER SHARK','NURSE SHARK','THRESHER','GOBLIN SHARK',
      'MEGALODON','DORSAL FIN','CARTILAGE','PREDATOR','MIGRATION',
      'ELECTROSENSE','BUOYANCY','TERRITORIAL','FEEDING'
    ],
    'Science': [
      'EXPERIMENT','CHEMICAL','MOLECULE','ELEMENT','HYDROGEN','OXYGEN',
      'PROTON','ELECTRON','ATOM','BEAKER','MICROSCOPE','GRAVITY',
      'VELOCITY','FRICTION','ENERGY','VOLTAGE','FORMULA','MAGNET',
      'LASER','PRISM','FLASK','CRYSTAL','REACT','CHARGE','FORCE',
      'COMPOUND','HYPOTHESIS','VARIABLE','OBSERVATION','CONCLUSION',
      'RADIATION','CONDENSER','CENTRIFUGE','TITRATION','DIFFUSION',
      'OSMOSIS','CATALYST','ELECTRODE','SPECTRUM','WAVELENGTH'
    ],
    'Construction': [
      'CRANE','CEMENT','HAMMER','WRENCH','SCAFFOLD','FOUNDATION',
      'BLUEPRINT','HARDHAT','FORKLIFT','DRILL','GIRDER','RIVET',
      'WELDING','LUMBER','MORTAR','CONCRETE','BOLT','BEAM','LOADER',
      'BUCKET','CHISEL','LEVEL','SHOVEL','NAIL','PLANK','EXCAVATOR',
      'BULLDOZER','JACKHAMMER','COMPACTOR','SURVEYOR','ARCHITECT',
      'INSULATION','DRYWALL','REBAR','AGGREGATE','CONTRACTOR','PERMIT',
      'SCAFFOLDING','TRUSS','MASONRY'
    ],
    'Bugs': [
      'BUTTERFLY','DRAGONFLY','LADYBUG','GRASSHOPPER','FIREFLY','CRICKET',
      'MANTIS','BEETLE','CATERPILLAR','CENTIPEDE','CICADA','BUMBLEBEE',
      'HORNET','TERMITE','APHID','EARWIG','MOTH','FLEA','GNAT','WASP',
      'ANT','FLY','TICK','MITE','GRUB','STICK INSECT','WALKINGSTICK',
      'MAYFLY','DAMSELFLY','LACEWING','WEEVIL','PILLBUG','SILVERFISH',
      'COCKROACH','LEAFCUTTER','TARANTULA','SCORPION','MILLIPEDE',
      'ASSASSIN BUG','WATER STRIDER'
    ],
    'Weather': [
      'THUNDER','LIGHTNING','TORNADO','BLIZZARD','HURRICANE','DRIZZLE',
      'FOGGY','CLOUDY','WINDY','RAINBOW','SUNSHINE','BAROMETER',
      'HUMIDITY','CELSIUS','CLIMATE','FORECAST','SNOWFLAKE','CYCLONE',
      'SLEET','FROST','BREEZE','STORM','GALE','HAIL','MIST','MONSOON',
      'TYPHOON','WATERSPOUT','SANDSTORM','THUNDERHEAD','PRECIPITATION',
      'TEMPERATURE','ATMOSPHERE','PRESSURE','FRONTAL','DEWPOINT',
      'WINDCHILL','HEATWAVE','DROUGHT','FLOODING'
    ],
    'Mythology': [
      'ZEUS','THOR','ODIN','POSEIDON','HERCULES','APOLLO','ARES','HADES',
      'ATLAS','TITAN','CYCLOPS','MEDUSA','MINOTAUR','HYDRA','GRIFFIN',
      'PEGASUS','PHOENIX','CENTAUR','CHIMERA','CERBERUS','ODYSSEUS',
      'ACHILLES','PERSEUS','TRITON','LOKI','FREYA','VALKYRIE','ASGARD',
      'OLYMPUS','LABYRINTH','THUNDERBOLT','TRIDENT','LEGEND','MYTH',
      'IMMORTAL','ORACLE','PROPHECY','DEMIGOD','UNDERWORLD','AMBROSIA'
    ],
    'Knights': [
      'KNIGHT','LANCE','SHIELD','CASTLE','JOUST','SQUIRE','FORTRESS',
      'DUNGEON','MOAT','DRAWBRIDGE','PORTCULLIS','BATTLEMENT','CATAPULT',
      'TREBUCHET','CROSSBOW','LONGBOW','CHAINMAIL','GAUNTLET','VISOR',
      'BROADSWORD','MACE','FLAIL','HALBERD','SIEGE','CONQUEST','CRUSADE',
      'CHIVALRY','FEUDAL','MONARCHY','PENNANT','HERALDRY','DESTRIER',
      'PAULDRON','VAMBRACE','BREASTPLATE','GREAVES','SABATON','SCABBARD',
      'RAMPART','TURRET'
    ],
    'Camping': [
      'CAMPFIRE','TENT','HIKING','COMPASS','LANTERN','CANTEEN','FISHING',
      'TRAIL','SUMMIT','FOREST','RIVER','KAYAK','CANOE','CLIMBING',
      'SURVIVAL','NAVIGATION','FIREWOOD','KINDLING','SMORES','CONSTELLATION',
      'NOCTURNAL','PREDATOR','FORAGE','SHELTER','TARP','HAMMOCK','BIVOUAC',
      'ORIENTEERING','TRAILHEAD','CAMPSITE','RANGER','WILDERNESS',
      'EXPEDITION','PATHFINDER','BACKPACK','RAPPELLING','WILDLIFE',
      'STARGAZING','BONFIRE','FLASHLIGHT'
    ],
    'Trains': [
      'LOCOMOTIVE','RAILROAD','CONDUCTOR','PASSENGER','FREIGHT','PLATFORM',
      'SIGNAL','CABOOSE','TENDER','BOXCAR','FLATCAR','TANKER','DIESEL',
      'ELECTRIC','MONORAIL','UNDERGROUND','DEPOT','TERMINUS','JUNCTION',
      'TRESTLE','TUNNEL','CROSSING','ROUNDHOUSE','TURNTABLE','COUPLING',
      'BOILER','PISTON','CYLINDER','WHISTLE','THROTTLE','GAUGE','TRACK',
      'RAILWAY','STATION','ENGINEER','COMMUTER','HIGHSPEED','STEAM',
      'CARRIAGE','SLEEPER'
    ],
    'Jungle': [
      'JUNGLE','EXPLORER','CANOPY','VINES','JAGUAR','PYTHON','GORILLA',
      'TOUCAN','MACAW','ANACONDA','PIRANHA','TREEFROG','CHAMELEON',
      'IGUANA','TARANTULA','CENTIPEDE','WATERFALL','TRIBUTARY','RAINFOREST',
      'BIODIVERSITY','CAMOUFLAGE','EXPEDITION','ADVENTURE','MACHETE',
      'QUICKSAND','TREEHOUSE','ZIPLINE','FOSSIL','ARTIFACT','INDIGENOUS',
      'TRIBE','DUGOUT','RAPIDS','HUMID','UNDERGROWTH','LIANA','BROMELIAD',
      'EPIPHYTE','HOWLER','TAPIR'
    ]
  },

  girl: {
    'Unicorns': [
      'UNICORN','RAINBOW','SPARKLE','MAGIC','GLITTER','CRYSTAL',
      'STARDUST','FAIRY','ENCHANT','SHIMMER','MOONBEAM','AURORA',
      'FANTASY','WISHES','MANE','HORN','WINGS','PRISM','GOLDEN',
      'RADIANT','STARLIGHT','DREAM','MEADOW','SPARK','MYSTICAL',
      'CELESTIAL','IRIDESCENT','LUMINOUS','ETHEREAL','WONDROUS',
      'GLIMMER','TWINKLE','OPALESCENT','WHIMSICAL','MAGICAL',
      'TRANSCENDENT','HOLOGRAPHIC','PASTEL','DEWDROP','MOONLIT'
    ],
    'Fairy Tales': [
      'PRINCESS','DRAGON','CASTLE','KNIGHT','WITCH','FAIRY','MAGIC',
      'SPELL','POTION','ENCHANT','FOREST','TOWER','KINGDOM','PRINCE',
      'FROG','APPLE','MIRROR','GLASS','WAND','CROWN','GOWN','CHARMING',
      'CURSE','WISH','BEAST','SORCERER','ENCHANTRESS','GOBLIN','DWARF',
      'GNOME','PIXIE','LEPRECHAUN','PROPHECY','QUEST','TALISMAN',
      'LEGENDARY','MAGICAL','ADVENTURE','TRANSFORMATION','HAPPILY'
    ],
    'Fashion': [
      'DRESS','SHOES','HANDBAG','NECKLACE','BRACELET','EARRINGS',
      'RIBBON','GLITTER','RUNWAY','FABRIC','PATTERN','VINTAGE',
      'BOUTIQUE','COUTURE','STYLISH','TRENDY','BLOUSE','SKIRT','SCARF',
      'BOOTS','VELVET','LACE','SILK','SATIN','SEQUIN','CASHMERE',
      'CHIFFON','EMBROIDERY','ACCESSORIES','WARDROBE','COLLECTION',
      'DESIGNER','TAILORED','ENSEMBLE','PALETTE','HEMLINE','PLATFORM',
      'STILETTO','CLUTCH','FASCINATOR'
    ],
    'Butterflies': [
      'BUTTERFLY','MONARCH','CHRYSALIS','PETAL','BLOSSOM','NECTAR',
      'LAVENDER','DAISY','VIOLET','TULIP','ORCHID','JASMINE','HONEYBEE',
      'CLOVER','SUNFLOWER','ROSEBUD','POPPY','LILY','DAHLIA','IRIS',
      'FLUTTER','BLOOM','FRAGRANT','MEADOW','GARDEN','MARIGOLD',
      'MAGNOLIA','WISTERIA','FOXGLOVE','BLUEBELL','DANDELION','PEONY',
      'CARNATION','HIBISCUS','CHRYSANTHEMUM','POLLINATE','METAMORPHOSIS',
      'MIGRATION','WINGSPAN','PROBOSCIS'
    ],
    'Mermaids': [
      'MERMAID','OCEAN','CORAL','PEARL','SHELL','SEAHORSE','DOLPHIN',
      'STARFISH','TREASURE','TRIDENT','CURRENT','LAGOON','SIREN',
      'SCALES','FINS','BUBBLES','KELP','AQUA','TIDE','WAVE','GROTTO',
      'REEF','FOAM','CREST','SWIM','ABALONE','NAUTILUS','TURQUOISE',
      'BIOLUMINESCENCE','UNDERTOW','WHIRLPOOL','DEPTHS','ENCHANTING',
      'GLIMMERING','SHIMMERING','IRIDESCENT','SALTWATER','DRIFTWOOD',
      'MOONPOOL','POSEIDON'
    ],
    'Ballet': [
      'BALLET','DANCER','POINTE','PIROUETTE','ARABESQUE','TUTU','BARRE',
      'RECITAL','STAGE','PERFORM','GRACEFUL','ELEGANT','RHYTHM',
      'REHEARSE','SPOTLIGHT','CURTAIN','APPLAUSE','COSTUME','LEAP',
      'TURN','POSE','MUSIC','GRACE','PLIE','TENDU','ALLEGRO','ADAGIO',
      'GRAND JETE','FOUETTE','RELEVE','ENTRECHAT','CHOREOGRAPHY',
      'CORPS DE BALLET','PRIMA','DEMI POINTE','BALLERINA','VARIATION',
      'DIVERTISSEMENT','GRAND BATTEMENT','ATTITUDE'
    ],
    'Horses': [
      'HORSE','SADDLE','BRIDLE','GALLOP','CANTER','TROT','MANE','HOOF',
      'STABLE','PASTURE','DRESSAGE','JUMPING','RIBBON','CHAMPION',
      'TRAINER','BRUSHING','GROOMING','MUSTANG','STALLION','MARE',
      'FOAL','PONY','COLT','FILLY','REINS','APPALOOSA','PALOMINO',
      'THOROUGHBRED','ARABIAN','QUARTERHORSE','SADDLERY','FARRIER',
      'VETERINARIAN','SHOWJUMPING','EQUESTRIAN','PADDOCK','LOPE',
      'BAREBACK','STEEPLECHASE','GYMKHANA'
    ],
    'Art and Crafts': [
      'PAINTING','DRAWING','SKETCHING','SCULPTURE','POTTERY','ORIGAMI',
      'COLLAGE','MOSAIC','WEAVING','KNITTING','SEWING','GLITTER',
      'STENCIL','PALETTE','CANVAS','BRUSHES','CREATE','DESIGN','CRAFT',
      'CLAY','BEADS','STAMP','PRINT','YARN','FABRIC','WATERCOLOR',
      'ACRYLIC','CHARCOAL','PASTEL','MIXED MEDIA','PHOTOGRAPHY',
      'CALLIGRAPHY','BOOKBINDING','MACRAME','FELTING','EMBROIDERY',
      'DECOUPAGE','LINOLEUM','PRINTMAKING','SILKSCREEN'
    ],
    'Baking': [
      'CUPCAKE','FROSTING','SPRINKLES','COOKIES','BROWNIE','MUFFIN',
      'PASTRY','BATTER','MIXING','VANILLA','CHOCOLATE','CINNAMON',
      'GINGER','RECIPE','MEASURE','DECORATE','SUGAR','CREAM','BUTTER',
      'FLOUR','ICING','FONDANT','GANACHE','GLAZE','SWIRL','MERINGUE',
      'SHORTBREAD','MACARON','PROFITEROLE','ECLAIR','CROISSANT',
      'SOURDOUGH','BRIOCHE','CHOUX PASTRY','CARAMEL','PRALINE',
      'MARZIPAN','BUTTERCREAM','LAMINATED','PIPING'
    ],
    'Princesses': [
      'AURORA','CINDERELLA','RAPUNZEL','ARIEL','BELLE','JASMINE',
      'TIANA','MULAN','MOANA','MERIDA','TIARA','GOWN','CASTLE',
      'BALLROOM','WALTZ','CROWN','SCEPTER','ROYAL','GRACE','CHARMING',
      'FAIRY','MAGIC','WAND','BALL','GLASS','KINGDOM','PALACE',
      'COURTIER','HANDMAIDEN','CHAMBERLAIN','CORONATION','CEREMONY',
      'BANQUET','PROCLAMATION','SOVEREIGN','ANCESTRY','HERITAGE',
      'MAJESTY','HERALD','THRONE'
    ],
    'Garden': [
      'SUNFLOWER','ROSEBUSH','DAISY','TULIP','LAVENDER','PLANTING',
      'WATERING','PRUNING','HARVEST','COMPOST','SEEDLING','TRELLIS',
      'BLOSSOM','PETAL','BUTTERFLY','LADYBUG','DRAGONFLY','HONEYBEE',
      'FERN','MULCH','SPADE','RAKE','HOSE','SOIL','BLOOM','TOPIARY',
      'PERGOLA','GREENHOUSE','PROPAGATION','FERTILIZER','IRRIGATION',
      'POLLINATOR','HEIRLOOM','PERENNIAL','BIENNIAL','DEADHEADING',
      'HARDENING OFF','RAISED BED','COMPANION PLANTING','VERMICULTURE'
    ],
    'Music': [
      'SINGING','DANCING','GUITAR','PIANO','VIOLIN','MELODY','HARMONY',
      'RHYTHM','CHORUS','LYRICS','CONCERT','PERFORM','MICROPHONE',
      'PLAYLIST','COMPOSE','NOTES','TEMPO','BEAT','SONG','STAGE',
      'AUDIENCE','SPOTLIGHT','ENCORE','SOLO','DUET','CRESCENDO',
      'DIMINUENDO','FORTISSIMO','PIANISSIMO','STACCATO','LEGATO',
      'ARPEGGIO','VIBRATO','TREMOLO','MODULATION','TRANSPOSITION',
      'IMPROVISATION','SYNCOPATION','COUNTERPOINT','SOLFEGE'
    ],
    'Cats': [
      'WHISKERS','PURRING','KITTEN','TABBY','SIAMESE','PERSIAN',
      'CALICO','FLUFFY','MEOWING','PAWING','STRETCHING','NAPPING',
      'PLAYFUL','CLIMBING','SCRATCHING','GROOMING','CURIOUS','ADORABLE',
      'YARN','POUNCE','HISS','PURR','FUR','PAW','LEAP','MAINE COON',
      'RAGDOLL','SCOTTISH FOLD','BENGAL','ABYSSINIAN','BIRMAN',
      'BURMESE','SPHYNX','NORWEGIAN','HIMALAYAN','SAVANNAH',
      'CHARTREUX','OCICAT','TONKINESE','BALINESE'
    ],
    'Gemstones': [
      'DIAMOND','RUBY','EMERALD','SAPPHIRE','PEARL','AMETHYST','TOPAZ',
      'OPAL','GARNET','CRYSTAL','NECKLACE','BRACELET','EARRINGS',
      'PENDANT','CHARM','LOCKET','TIARA','GEMSTONE','JEWEL','SPARKLE',
      'FACET','CARAT','GOLD','SILVER','PLATINUM','TURQUOISE','PERIDOT',
      'ALEXANDRITE','TANZANITE','AQUAMARINE','MOONSTONE','LABRADORITE',
      'MALACHITE','TOURMALINE','CITRINE','IOLITE','SPINEL',
      'ZIRCON','RHODONITE','CHRYSOPRASE'
    ],
    'Rainbows': [
      'RED','ORANGE','YELLOW','GREEN','BLUE','PURPLE','PINK','TURQUOISE',
      'CRIMSON','VIOLET','INDIGO','MAGENTA','SCARLET','LAVENDER','TEAL',
      'MAROON','GOLDEN','RAINBOW','PRISM','SPECTRUM','VIBRANT','PASTEL',
      'BRIGHT','VIVID','RADIANT','CERULEAN','VERMILLION','CHARTREUSE',
      'FUCHSIA','PERIWINKLE','COBALT','AMBER','OCHRE','SIENNA',
      'ULTRAMARINE','VIRIDIAN','BURGUNDY','MAUVE','CHAMPAGNE','IVORY'
    ],
    'Spa and Beauty': [
      'SPA','MASSAGE','FACIAL','MANICURE','PEDICURE','SKINCARE',
      'MOISTURIZER','CLEANSER','TONER','SERUM','EXFOLIATE','AROMATHERAPY',
      'LAVENDER','ROSEWATER','CUCUMBER','BUBBLEBATH','LOOFAH','SCRUB',
      'RELAXATION','MEDITATION','WELLNESS','BLISS','RENEWAL','TRANQUIL',
      'SERENE','REJUVENATE','PAMPER','LUXURIOUS','RADIANT','GLOWING',
      'REFRESH','RESTORE','REVITALIZE','TREATMENT','RITUAL','INDULGE',
      'SANCTUARY','STEAM','INFUSION','DETOX'
    ],
    'Dogs and Puppies': [
      'PUPPY','GOLDEN','LABRADOR','POODLE','BULLDOG','HUSKY','BEAGLE',
      'DACHSHUND','COLLIE','SPANIEL','RETRIEVER','SHEPHERD','TERRIER',
      'DALMATIAN','CHIHUAHUA','POMERANIAN','CORGI','SHIHTZU','BICHON',
      'MALTESE','FETCH','WALKIES','GROOMING','TRAINING','CUDDLE',
      'PLAYFUL','LOYAL','OBEDIENT','BISCUITS','LEASH','COLLAR','HARNESS',
      'KENNEL','AGILITY','OBEDIENCE','PAWPRINT','WAGGING','SNUGGLE',
      'ADORABLE','FUREVER'
    ],
    'Tea Party': [
      'TEAPOT','TEACUP','SAUCER','BISCUIT','SCONE','CREAM','SANDWICH',
      'CAKE','LEMON','STRAINER','INFUSER','CHAMOMILE','EARLGREY',
      'PEPPERMINT','JASMINE','OOLONG','HERBAL','DARJEELING','TABLECLOTH',
      'NAPKIN','CENTERPIECE','INVITATION','HOSTESS','ETIQUETTE','DAINTY',
      'DELIGHTFUL','CHARMING','FLORAL','WHIMSICAL','TIERED','DOILY',
      'CHINA','PORCELAIN','LACE','PARASOL','PINKIE','FRAGRANT','ELEGANT',
      'REFINED','GRACIOUS'
    ],
    'Travel': [
      'PASSPORT','ADVENTURE','JOURNEY','EXPLORE','DISCOVER','CULTURE',
      'LANDMARK','MUSEUM','CUISINE','SOUVENIR','PHOTOGRAPH','LUGGAGE',
      'BOARDING','DESTINATION','ITINERARY','HORIZON','COMPASS','GUIDEBOOK',
      'LANGUAGE','CURRENCY','FESTIVAL','TRADITION','ARCHITECTURE',
      'MONUMENT','WATERFALL','ISLAND','MOUNTAIN','SAFARI','CRUISE',
      'BACKPACKING','HOSTEL','RESORT','HERITAGE','WANDERLUST','NOMAD',
      'GLOBETROTTER','EXPEDITION','ODYSSEY','VOYAGE','EXCURSION'
    ],
    'Cooking': [
      'RECIPE','INGREDIENTS','CHOP','DICE','MINCE','SAUTE','SIMMER',
      'BOIL','ROAST','GRILL','STEAM','BLEND','WHISK','FOLD','MARINATE',
      'SEASON','GARNISH','PLATE','FLAVOR','AROMA','TEXTURE','CUISINE',
      'CHEF','APRON','SPATULA','LADLE','TONGS','COLANDER','GRATER',
      'PEELER','MORTAR','PESTLE','STOCKPOT','RAMEKIN','THERMOMETER',
      'REDUCTION','BRAISE','DEGLAZE','JULIENNE','ZEST'
    ]
  },

  general: {
    'Animals': [
      'ELEPHANT','GIRAFFE','PENGUIN','DOLPHIN','CHEETAH','KANGAROO',
      'PANDA','GORILLA','FLAMINGO','PARROT','OCTOPUS','CROCODILE',
      'HEDGEHOG','ARMADILLO','PLATYPUS','WOLVERINE','CHAMELEON',
      'NARWHAL','WALRUS','CAPYBARA','SLOTH','KOALA','JAGUAR','LEMUR',
      'TAPIR','AXOLOTL','QUOKKA','BINTURONG','FOSSA','OKAPI',
      'MANDRILL','CASSOWARY','GHARIAL','MONITOR LIZARD','SECRETARY BIRD',
      'PROBOSCIS MONKEY','PANGOLIN','SAIGA','BONGO','GERENUK'
    ],
    'Food': [
      'PIZZA','BURGER','SPAGHETTI','SUSHI','TACOS','PANCAKES','WAFFLES',
      'SANDWICH','HOTDOG','POPCORN','LASAGNA','BURRITO','NOODLES',
      'PRETZEL','MEATBALL','CROISSANT','DUMPLING','KEBAB','NACHOS',
      'SMOOTHIE','FALAFEL','STRUDEL','QUICHE','FONDUE','CREPE','PAELLA',
      'POUTINE','EMPANADA','PIEROGI','SHAKSHUKA','BIBIMBAP','PHO',
      'RAMEN','GOULASH','TAGINE','MOUSSAKA','CEVICHE','BAKLAVA',
      'TIRAMISU','CHURROS'
    ],
    'Fruits and Vegetables': [
      'APPLE','BANANA','STRAWBERRY','WATERMELON','PINEAPPLE','MANGO',
      'BLUEBERRY','PEACH','CHERRY','KIWI','LEMON','COCONUT','BROCCOLI',
      'CARROT','SPINACH','TOMATO','AVOCADO','CUCUMBER','PUMPKIN',
      'ZUCCHINI','RADISH','TURNIP','ASPARAGUS','CELERY','PAPAYA',
      'DRAGONFRUIT','STARFRUIT','DURIAN','JACKFRUIT','PERSIMMON',
      'POMEGRANATE','RAMBUTAN','PASSION FRUIT','ARTICHOKE','KOHLRABI',
      'FENNEL','PARSNIP','RUTABAGA','CHARD','ENDIVE'
    ],
    'Weather': [
      'SUNSHINE','RAINBOW','THUNDER','LIGHTNING','TORNADO','BLIZZARD',
      'HURRICANE','DRIZZLE','FOGGY','CLOUDY','WINDY','HAILSTORM',
      'FORECAST','BAROMETER','HUMIDITY','CELSIUS','CLIMATE','SNOWFLAKE',
      'CYCLONE','BREEZE','FROST','SLEET','GALE','STORM','MIST','MONSOON',
      'TYPHOON','WATERSPOUT','SANDSTORM','THUNDERHEAD','PRECIPITATION',
      'TEMPERATURE','ATMOSPHERE','PRESSURE','FRONTAL','DEWPOINT',
      'WINDCHILL','HEATWAVE','DROUGHT','FLOODING'
    ],
    'School': [
      'PENCIL','NOTEBOOK','BACKPACK','TEACHER','HOMEWORK','LIBRARY',
      'SCIENCE','HISTORY','READING','WRITING','SPELLING','CAFETERIA',
      'PLAYGROUND','PRINCIPAL','CLASSROOM','STUDENT','LESSON','PROJECT',
      'DIPLOMA','RECESS','SCHEDULE','LOCKER','HALLWAY','LUNCHBOX','CHALK',
      'TEXTBOOK','CALCULATOR','PROTRACTOR','COMPASS','HIGHLIGHTER',
      'BINDER','PORTFOLIO','DETENTION','GRADUATION','EXTRACURRICULAR',
      'ASSEMBLY','LABORATORY','GYMNASIUM','AUDITORIUM','COUNSELOR'
    ],
    'Ocean Life': [
      'DOLPHIN','WHALE','OCTOPUS','LOBSTER','SEAHORSE','JELLYFISH',
      'STARFISH','SEAWEED','TSUNAMI','SUBMARINE','CORAL','ANEMONE',
      'MANATEE','NARWHAL','SWORDFISH','BARRACUDA','TUNA','CRAB','ORCA',
      'SQUID','PUFFERFISH','CLOWNFISH','ANCHOVY','HALIBUT','GROUPER',
      'MANTIS SHRIMP','ANGLERFISH','VIPERFISH','BLOBFISH','COELACANTH',
      'MORAY EEL','LIONFISH','STONEFISH','MANTA RAY','HAMMERHEAD',
      'GIANT SQUID','NUDIBRANCH','SEA SLUG','CHITON','HORSESHOE CRAB'
    ],
    'Farm': [
      'TRACTOR','CHICKEN','ROOSTER','PIGLET','SHEEPDOG','DONKEY',
      'HAYSTACK','BARNYARD','HARVEST','SCARECROW','COMBINE','LIVESTOCK',
      'PASTURE','MEADOW','ORCHARD','CROPS','SILO','FARMHOUSE','GOAT',
      'TURKEY','RABBIT','BEEHIVE','CORNFIELD','FENCE','COOP','IRRIGATION',
      'WINDMILL','GREENHOUSE','COMPOSTING','CROP ROTATION','LIVESTOCK',
      'VETERINARIAN','MILKING','SHEARING','PLOWING','SEEDING',
      'THRESHING','CULTIVATOR','HERBICIDE','PESTICIDE'
    ],
    'Holidays': [
      'CHRISTMAS','HALLOWEEN','THANKSGIVING','EASTER','BIRTHDAY',
      'VALENTINE','HANUKKAH','DIWALI','FIREWORKS','CELEBRATE','PRESENT',
      'COSTUME','PUMPKIN','TURKEY','CANDLES','PARADE','FESTIVAL',
      'DECORATE','FAMILY','GATHER','TRADITION','RIBBON','WRAPPING',
      'ORNAMENT','STOCKING','KWANZAA','RAMADAN','CHINESE NEW YEAR',
      'MARDI GRAS','PASSOVER','BONFIRE NIGHT','OKTOBERFEST','CARNIVAL',
      'SOLSTICE','EQUINOX','REMEMBRANCE','INDEPENDENCE','LANTERN',
      'MENORAH','ADVENT'
    ],
    'Countries': [
      'FRANCE','BRAZIL','JAPAN','AUSTRALIA','CANADA','MEXICO','GERMANY',
      'ITALY','CHINA','RUSSIA','SPAIN','EGYPT','INDIA','KENYA','NORWAY',
      'SWEDEN','GREECE','TURKEY','ARGENTINA','THAILAND','PERU','CHILE',
      'POLAND','UKRAINE','VIETNAM','INDONESIA','MOROCCO','NIGERIA',
      'ETHIOPIA','COLOMBIA','VENEZUELA','BANGLADESH','PAKISTAN',
      'PHILIPPINES','MALAYSIA','PORTUGAL','HUNGARY','FINLAND',
      'DENMARK','SWITZERLAND'
    ],
    'Instruments': [
      'GUITAR','PIANO','VIOLIN','TRUMPET','DRUMS','FLUTE','SAXOPHONE',
      'CELLO','KEYBOARD','HARP','ACCORDION','CLARINET','TROMBONE',
      'BASSOON','UKULELE','BANJO','HARMONICA','OBOE','CYMBAL',
      'XYLOPHONE','MANDOLIN','SITAR','BONGO','ZITHER','DULCIMER',
      'DIDGERIDOO','BALALAIKA','ERHU','SHAMISEN','BOUZOUKI','KOTO',
      'MBIRA','STEEL DRUM','MARIMBA','VIBRAPHONE','THEREMIN','HURDY GURDY',
      'LUTE','RECORDER','BAGPIPES'
    ],
    'Space and Planets': [
      'MERCURY','VENUS','EARTH','MARS','JUPITER','SATURN','URANUS',
      'NEPTUNE','PLUTO','MOON','ASTEROID','COMET','GALAXY','NEBULA',
      'PULSAR','SUPERNOVA','COSMOS','UNIVERSE','ROCKET','ASTRONAUT',
      'ORBIT','GRAVITY','TELESCOPE','CRATER','SHUTTLE','QUASAR',
      'DARK MATTER','DARK ENERGY','EXOPLANET','SOLAR WIND','MAGNETOSPHERE',
      'AURORA BOREALIS','COSMIC RAY','EVENT HORIZON','NEUTRON STAR',
      'WHITE DWARF','RED GIANT','BINARY STAR','GLOBULAR CLUSTER','PARALLAX'
    ],
    'Nature': [
      'MOUNTAIN','VOLCANO','WATERFALL','CANYON','GLACIER','FOREST',
      'MEADOW','DESERT','SWAMP','TUNDRA','SAVANNA','JUNGLE','RAINFOREST',
      'PRAIRIE','PLATEAU','LAGOON','ESTUARY','DELTA','PENINSULA',
      'ARCHIPELAGO','CLIFF','VALLEY','RIDGE','GORGE','CAVERN','FJORD',
      'ATOLL','GEYSER','HOTSPRING','PERMAFROST','MANGROVE','WETLAND',
      'CHAPARRAL','TAIGA','STEPPE','FLOODPLAIN','DRUMLIN','MORAINE',
      'SINKHOLE','CENOTE'
    ],
    'Sports': [
      'FOOTBALL','BASEBALL','SOCCER','HOCKEY','TENNIS','SWIMMING',
      'TROPHY','ATHLETE','CHAMPION','VICTORY','REFEREE','PENALTY',
      'TACKLE','SPRINT','SCORE','TEAM','COACH','GOAL','MEDAL','REBOUND',
      'PITCHER','GOALIE','ASSIST','SERVE','VOLLEY','GYMNASTICS',
      'WRESTLING','ARCHERY','FENCING','CYCLING','TRIATHLON','DECATHLON',
      'BOBSLED','BIATHLON','CURLING','WEIGHTLIFTING','SYNCHRONIZED',
      'EQUESTRIAN','PENTATHLON','MARATHON'
    ],
    'Birds': [
      'EAGLE','PENGUIN','FLAMINGO','PARROT','TOUCAN','PEACOCK','HAWK',
      'FALCON','SPARROW','ROBIN','CARDINAL','BLUEBIRD','HUMMINGBIRD',
      'WOODPECKER','OWL','PELICAN','STORK','CRANE','HERON','ALBATROSS',
      'OSPREY','PUFFIN','KINGFISHER','SWALLOW','MARTIN','CASSOWARY',
      'KOOKABURRA','SECRETARY BIRD','SHOEBILL','KAKAPO','RESPLENDENT',
      'QUETZAL','LYREBIRD','BOWERBIRD','FRIGATE BIRD','TROPICBIRD',
      'ROADRUNNER','ANHINGA','SUNBITTERN','HOATZIN'
    ],
    'Family': [
      'FAMILY','MOTHER','FATHER','SISTER','BROTHER','GRANDMA','GRANDPA',
      'COUSIN','KITCHEN','BEDROOM','BATHROOM','GARDEN','GARAGE',
      'BASEMENT','BACKYARD','FIREPLACE','CHIMNEY','MAILBOX','DRIVEWAY',
      'HALLWAY','WINDOW','CURTAIN','BOOKSHELF','PANTRY','PORCH',
      'STEPPARENT','GUARDIAN','CAREGIVER','NEWBORN','TODDLER',
      'ADOLESCENT','TEENAGER','ANCESTOR','GENEALOGY','HERITAGE',
      'REUNION','TRADITION','HOUSEHOLD','SIBLING','EXTENDED'
    ],
    'Transportation': [
      'CAR','TRUCK','BUS','TRAIN','AIRPLANE','HELICOPTER','MOTORCYCLE',
      'BICYCLE','BOAT','SUBMARINE','ROCKET','TRAM','METRO','FERRY',
      'TAXI','AMBULANCE','HOVERCRAFT','HYDROFOIL','CATAMARAN','ZEPPELIN',
      'BLIMP','CABLECAR','RICKSHAW','GONDOLA','SNOWMOBILE','MONORAIL',
      'MAGLEV','HYPERLOOP','AVIATION','NAUTICAL','TRANSIT','COMMUTE',
      'FREIGHT','CARGO','VESSEL','PROPELLER','FUSELAGE','RUDDER',
      'THROTTLE','NAVIGATION'
    ],
    'Human Body': [
      'HEART','BRAIN','LUNGS','LIVER','KIDNEY','STOMACH','MUSCLE',
      'BONE','SKIN','BLOOD','NERVE','ARTERY','VEIN','SPINE','SKULL',
      'RIBCAGE','PELVIS','FEMUR','TIBIA','PATELLA','HUMERUS','RADIUS',
      'ULNA','VERTEBRA','CARTILAGE','TENDON','LIGAMENT','SYNAPSE',
      'NEURON','HORMONE','ENZYME','PLATELET','ANTIBODY','CHROMOSOME',
      'DIGESTION','RESPIRATION','CIRCULATION','IMMUNITY','METABOLISM',
      'MITOSIS'
    ],
    'Technology': [
      'COMPUTER','INTERNET','SMARTPHONE','TABLET','LAPTOP','KEYBOARD',
      'MONITOR','PROCESSOR','MEMORY','STORAGE','WIFI','BLUETOOTH',
      'SOFTWARE','HARDWARE','APPLICATION','ALGORITHM','DATABASE',
      'NETWORK','SERVER','CLOUD','CYBERSECURITY','ENCRYPTION','FIREWALL',
      'STREAMING','DOWNLOAD','UPLOAD','PIXEL','RESOLUTION','TOUCHSCREEN',
      'AUTOMATION','PROGRAMMING','CODING','DEBUGGING','INTERFACE',
      'BANDWIDTH','VIRTUAL','AUGMENTED','BLOCKCHAIN','BIOMETRIC','QUANTUM'
    ],
    'Ancient History': [
      'PYRAMID','PHARAOH','SPHINX','MUMMY','HIEROGLYPH','COLOSSEUM',
      'GLADIATOR','EMPEROR','LEGION','AQUEDUCT','ACROPOLIS','PARTHENON',
      'PHILOSOPHER','DEMOCRACY','OLYMPIAD','DYNASTY','SAMURAI','SHOGUN',
      'FEUDAL','VIKING','LONGSHIP','MONASTERY','CRUSADE','CATHEDRAL',
      'RENAISSANCE','CONQUISTADOR','AZTEC','MAYAN','INCA','TERRACOTTA',
      'ARISTOTLE','CLEOPATRA','CAESAR','HANNIBAL','ALEXANDER','CUNEIFORM',
      'MESOPOTAMIA','CIVILIZATION','ARCHAEOLOGY','PAPYRUS'
    ],
    'World Mythology': [
      'ZEUS','THOR','ODIN','POSEIDON','HERCULES','APOLLO','ARES','HADES',
      'ATLAS','TITAN','CYCLOPS','MEDUSA','MINOTAUR','HYDRA','GRIFFIN',
      'PEGASUS','PHOENIX','CENTAUR','CHIMERA','CERBERUS','ANUBIS',
      'OSIRIS','BASTET','VISHNU','BRAHMA','SHIVA','QUETZALCOATL',
      'ANANSI','LOKI','FREYA','VALKYRIE','KITSUNE','TENGU','THUNDERBIRD',
      'DJINN','GOLEM','BANSHEE','RAVEN','SPHINX','LEGEND'
    ]
  }

};

// ============================================================
// DIFFICULTY CONFIG
// ============================================================
const DIFFICULTY = {
  easy:   { size: 10, wordCount: 10 },
  medium: { size: 15, wordCount: 15 },
  hard:   { size: 20, wordCount: 20 }
};

// ============================================================
// WORD SEARCH ALGORITHM
// ============================================================
const DIRECTIONS = [
  [ 0,  1], // right
  [ 0, -1], // left
  [ 1,  0], // down
  [-1,  0], // up
  [ 1,  1], // down-right
  [ 1, -1], // down-left
  [-1,  1], // up-right
  [-1, -1]  // up-left
];

function shuffle(arr) {
  const a = arr.slice();
  for (let i = a.length - 1; i > 0; i--) {
    const j = Math.floor(Math.random() * (i + 1));
    [a[i], a[j]] = [a[j], a[i]];
  }
  return a;
}

function canPlace(grid, word, row, col, dr, dc) {
  const size = grid.length;
  for (let i = 0; i < word.length; i++) {
    const r = row + i * dr;
    const c = col + i * dc;
    if (r < 0 || r >= size || c < 0 || c >= size) return false;
    if (grid[r][c] && grid[r][c] !== word[i]) return false;
  }
  return true;
}

function placeWord(grid, word, row, col, dr, dc) {
  for (let i = 0; i < word.length; i++) {
    grid[row + i * dr][col + i * dc] = word[i];
  }
}

function generateGrid(size, words) {
  const grid = Array.from({ length: size }, () => Array(size).fill(''));
  const placed = [];

  for (const word of words) {
    // Build all possible (row, col, direction) placements and shuffle
    const tries = [];
    for (let r = 0; r < size; r++) {
      for (let c = 0; c < size; c++) {
        for (const [dr, dc] of DIRECTIONS) {
          tries.push([r, c, dr, dc]);
        }
      }
    }
    const shuffled = shuffle(tries);

    for (const [r, c, dr, dc] of shuffled) {
      if (canPlace(grid, word, r, c, dr, dc)) {
        placeWord(grid, word, r, c, dr, dc);
        placed.push(word);
        break;
      }
    }
  }

  // Fill empty cells with random letters
  const alpha = 'ABCDEFGHIJKLMNOPQRSTUVWXYZ';
  for (let r = 0; r < size; r++) {
    for (let c = 0; c < size; c++) {
      if (!grid[r][c]) {
        grid[r][c] = alpha[Math.floor(Math.random() * 26)];
      }
    }
  }

  return { grid, placed };
}

// ============================================================
// DOM HELPERS
// ============================================================
function populateTopics(gender) {
  const topicEl = document.getElementById('topic');
  const topics = Object.keys(WORD_LISTS[gender]);
  topicEl.innerHTML = topics.map(t =>
    `<option value="${t}">${t}</option>`
  ).join('');
}

function renderGrid(grid, size) {
  const el = document.getElementById('ws-grid');
  el.style.gridTemplateColumns = `repeat(${size}, 32px)`;
  el.style.setProperty('--cols', size);
  el.setAttribute('data-size', size);
  el.innerHTML = '';

  for (const row of grid) {
    for (const letter of row) {
      const cell = document.createElement('div');
      cell.className = 'ws-cell';
      cell.textContent = letter;
      el.appendChild(cell);
    }
  }
}

function renderWordList(words) {
  const el = document.getElementById('word-list-items');
  el.innerHTML = words.map(w =>
    `<span class="word-item">${w}</span>`
  ).join('');
}

// ============================================================
// GENERATE
// ============================================================
function generate() {
  const diffKey  = document.getElementById('difficulty').value;
  const gender   = document.getElementById('gender').value;
  const topic    = document.getElementById('topic').value;

  const { size, wordCount } = DIFFICULTY[diffKey];
  const pool = WORD_LISTS[gender][topic];

  // Filter to words that fit in the grid, then randomly pick wordCount of them
  const eligible = pool.filter(w => w.length <= size);
  const selected = shuffle(eligible).slice(0, wordCount);

  const { grid, placed } = generateGrid(size, selected);

  // Titles
  document.getElementById('puzzle-title').textContent = `${topic} Word Search`;
  document.getElementById('puzzle-subtitle').textContent =
    `Find all ${placed.length} hidden words!`;

  renderGrid(grid, size);
  renderWordList(placed.slice().sort());

  const output = document.getElementById('output');
  output.classList.remove('hidden');
  output.scrollIntoView({ behavior: 'smooth', block: 'start' });
}

// ============================================================
// INIT
// ============================================================
document.addEventListener('DOMContentLoaded', () => {
  const genderEl   = document.getElementById('gender');
  const generateEl = document.getElementById('generate-btn');
  const regenEl    = document.getElementById('regen-btn');
  const printEl    = document.getElementById('print-btn');

  populateTopics(genderEl.value);

  genderEl.addEventListener('change', () => populateTopics(genderEl.value));
  generateEl.addEventListener('click', generate);
  regenEl.addEventListener('click', generate);
  printEl.addEventListener('click', () => window.print());
});
